server {
    listen 80;
    server_name _;
    absolute_redirect off;
    port_in_redirect off;
    root /usr/share/nginx/html;
    index index.html;

    location = /docker/levi {
        return 301 /docker/levi/;
    }

    location /docker/levi/ {
        try_files $uri $uri/ =404;
    }

    location / {
        return 404;
    }
}
